stages:
  - build
  - deploy

build:
  stage: build
  image: golang:latest
  script:
    - go build -o app
  artifacts:
    paths:
      - app

deploy:
  stage: deploy
  image: python:latest
  script:
    - apt-get update && apt-get install -y bash
    - pip install --upgrade awscli
    - aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
    - aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
    - aws configure set region $AWS_REGION
    - $(aws ecr get-login --no-include-email --region $AWS_REGION)
    - docker build -t $ECR_REPOSITORY:latest .
    - docker push $ECR_REPOSITORY:latest
    - aws ecs update-service --cluster your-cluster-name --service your-service-name --force-new-deployment
